import { getLangByResId } from '../../pub/tool/multiLangUtil';

function getTableMeta() {
	const tableMeta = {
		head: {
			items: [
				{
					hyperlinkflag: false,
					islock: false,
					istotal: false,
					attrcode: 'fieldname',
					containlower: false,
					datatype: '1',
					disabled: true,
					editAfterFlag: false,
					fieldDisplayed: 'refcode',
					fieldValued: 'refpk',
					isDataPowerEnable: true,
					isnotmeta: false,
					isResLabel: false,
					isrevise: false,
					isShowUnit: false,
					itemtype: 'input',
					label: getLangByResId(this, '4001SMARTPROVIDER-000022') /* 国际化处理： 字段编码*/,
					maxlength: '50',
					position: '137',
					required: false,
					scale: '0',
					visible: true
				},
				{
					hyperlinkflag: false,
					islock: false,
					istotal: false,
					attrcode: 'multilangtext',
					containlower: false,
					datatype: '1',
					disabled: true,
					editAfterFlag: false,
					fieldDisplayed: 'refcode',
					fieldValued: 'refpk',
					isDataPowerEnable: true,
					isnotmeta: false,
					isResLabel: false,
					isrevise: false,
					isShowUnit: false,
					itemtype: 'input',
					label: getLangByResId(this, '4001SMARTPROVIDER-000023') /* 国际化处理： 字段名称*/,
					maxlength: '50',
					position: '137',
					required: false,
					scale: '0',
					visible: true
				},
				{
					hyperlinkflag: false,
					islock: false,
					istotal: false,
					attrcode: 'datatype',
					containlower: false,
					datatype: '1',
					disabled: true,
					editAfterFlag: false,
					fieldDisplayed: 'refcode',
					fieldValued: 'refpk',
					isDataPowerEnable: true,
					isnotmeta: false,
					isResLabel: false,
					isrevise: false,
					isShowUnit: false,
					itemtype: 'input',
					label: getLangByResId(this, '4001SMARTPROVIDER-000024') /* 国际化处理： 数据类型*/,
					maxlength: '50',
					position: '137',
					required: false,
					scale: '0',
					visible: true
				},
				{
					hyperlinkflag: false,
					islock: false,
					istotal: false,
					attrcode: 'precision',
					containlower: false,
					datatype: '1',
					disabled: true,
					editAfterFlag: false,
					fieldDisplayed: 'refcode',
					fieldValued: 'refpk',
					isDataPowerEnable: true,
					isnotmeta: false,
					isResLabel: false,
					isrevise: false,
					isShowUnit: false,
					itemtype: 'input',
					label: getLangByResId(this, '4001SMARTPROVIDER-000025') /* 国际化处理： 位数*/,
					maxlength: '50',
					position: '137',
					required: false,
					scale: '0',
					visible: true
				},
				{
					hyperlinkflag: false,
					islock: false,
					istotal: false,
					attrcode: 'scale',
					containlower: false,
					datatype: '1',
					disabled: true,
					editAfterFlag: false,
					fieldDisplayed: 'refcode',
					fieldValued: 'refpk',
					isDataPowerEnable: true,
					isnotmeta: false,
					isResLabel: false,
					isrevise: false,
					isShowUnit: false,
					itemtype: 'input',
					label: getLangByResId(this, '4001SMARTPROVIDER-000026') /* 国际化处理： 精度*/,
					maxlength: '50',
					position: '137',
					required: false,
					scale: '0',
					visible: true
				}
			],
			moduletype: 'table',
			areaVisible: true,
			pagination: false,
			code: 'head',
			name: '表头列表'
		}
	};

	return tableMeta;
}

export { getTableMeta };
